'use client';
import './globals.css'
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <DndProvider backend={HTML5Backend}>
        <body>{children}</body>
      </DndProvider>
    </html>
  )
}
